### ISSUE TITLE
StackOverflow

### ISSUE THREAD

**Issue by betomaluje** [Catapush/catapush-android-sdk-example#2]
Hi guys, we are implementing the sdk successfully but there are cases when sometimes we get a really bad crash report:

``````
Fatal Exception: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
   at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.StackOverflowError: stack size 1037KB
   at java.lang.Class.isInstance(Class.java:1318)
   at java.util.EnumMap.isValidKeyType(EnumMap.java:724)
   at java.util.EnumMap.get(EnumMap.java:573)
   at android.net.NetworkInfo.setDetailedState(NetworkInfo.java:364)
   at android.net.NetworkInfo.<init>(NetworkInfo.java:140)
   at android.net.NetworkInfo$1.createFromParcel(NetworkInfo.java:459)
   at android.net.NetworkInfo$1.createFromParcel(NetworkInfo.java:453)
   at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:1114)
   at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:705)
   at com.catapush.library.connection.ConnectivityStatusManager.isAvailable(ConnectivityStatusManager.java:56)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:136)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)
   at com.jakewharton.rxrelay.RelaySubscriptionManager$RelayObserver.onNext(RelaySubscriptionManager.java:208)
   at com.jakewharton.rxrelay.PublishRelay.call(PublishRelay.java:47)
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.connect(XmppConnectionManager.java:304)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:144)
   at com.catapush.library.xmpp.XmppErrorManager$3.onNext(XmppErrorManager.java:120)
   at rx.internal.util.ObserverSubscriber.onNext(ObserverSubscriber.java:34)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:249)```
``````

....

```
   at com.catapush.library.xmpp.XmppConnectionManager.authenticate(XmppConnectionManager.java:397)
   at com.catapush.library.xmpp.XmppConnectionManager.access$300(XmppConnectionManager.java:61)
   at com.catapush.library.xmpp.XmppConnectionManager$1.connected(XmppConnectionManager.java:92)
   at org.jivesoftware.smack.AbstractXMPPConnection.callConnectionConnectedListener(AbstractXMPPConnection.java:1162)
   at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:858)
   at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:364)
   at com.catapush.library.xmpp.XmppConnectionManager.lambda$connect$26(XmppConnectionManager.java:344)
   at com.catapush.library.xmpp.XmppConnectionManager$$Lambda$7.call(Unknown Source)
   at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
   at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
   at rx.internal.operators.OperatorDistinctUntilChanged$1.onNext(OperatorDistinctUntilChanged.java:78)
   at rx.internal.operators.OperatorFilter$FilterSubscriber.onNext(OperatorFilter.java:73)
   at rx.internal.operators.OperatorZip$Zip.tick(OperatorZip.java:264)
   at rx.internal.operators.OperatorZip$Zip$InnerSubscriber.onNext(OperatorZip.java:335)
   at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:86)
   at com.catapush.library.storage.StorageManager.lambda$get$17(StorageManager.java:98)
   at com.catapush.library.storage.StorageManager$$Lambda$7.call(Unknown Source)
   at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
   at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   at rx.Observable.unsafeSubscribe(Observable.java:8666)
   at rx.internal.operators.OperatorZip$Zip.start(OperatorZip.java:214)
   at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:156)
   at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:122)
   at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:284)
   at rx.Subscriber.setProducer(Subscriber.java:209)
   at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:146)
   at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:137)
   at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
   at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
   at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
   at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
   at rx.Observable.unsafeSubscribe(Observable.java:8666)
   at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
   at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
   at java.lang.Thread.run(Thread.java:818)
```

And goes on infinetly. The whole issue can be found here: https://dl.dropboxusercontent.com/u/14652069/com.cornershopapp.shopper.android_issue_277_crash_57aa5516020800014b2907cbb7215cb3.txt
(github doesn't allowed me to publish more than 65536 characters in this issue)

Hope you guys can help us

PS: I couldn't find the SDK repository that's why I'm posting this here

**Comment by davidemarrone** [comment]
fixed in the new official version
